name: Workflow Demo

on: 
  # push
  schedule:
    - cron: '20 15 * * *'

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Kolkata'

    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID
    